#!/usr/bin/env python

import os
import sys

import torch
from diffusers import StableDiffusionPipeline

os.makedirs("diffusers-cache", exist_ok=True)


pipe = StableDiffusionPipeline.from_pretrained(
    "Linaqruf/anything-v3.0",
    cache_dir="diffusers-cache",
    use_auth_token=sys.argv[1],
)
